{"clientId":"15",
  "productId":37,
  "disbursementData":[],
  "principal":50000,
  "loanTermFrequency":"30",
  "loanTermFrequencyType":0,
  "numberOfRepayments":1,
  "repaymentEvery":30,
  "repaymentFrequencyType":0,
  "interestRatePerPeriod":24,
  "amortizationType":1,
  "interestType":0,
  "interestCalculationPeriodType":1,
  "graceOnArrearsAgeing":5,
  "transactionProcessingStrategyId":6,
  "locale":"en","dateFormat":"dd MMMM yyyy",
  "loanType":"individual",
  "expectedDisbursementDate":"20 July 2015",
  "submittedOnDate":"18 July 2015",
  "charges":[{"chargeId":7,"amount":1.5}]
}
